## Python Exercises - Session 3: Control Flow & Strings
The exercises below are organized to match [A Whirlwind Tour of Python (VanderPlas)](https://jakevdp.github.io/WhirlwindTourOfPython/). Specific pages are referenced in the various sections. These are designed to run using Python 3.6.

Follow the guidelines below. Where necessary replace the ellipses (`...`) with the appropriate code in the code blocks, the run the code by pressing ctrl-enter. Be sure to save your document before closing. 

---
### 3.1 Conditional Statements: `if`, `elif`, and `else` ([p 38](http://nbviewer.jupyter.org/github/env859/WhirlwindTourOfPython/blob/master/07-Control-Flow-Statements.ipynb))
##### What to know
* Using the `if` statement to control what code gets run
  * Use of the colon, Boolean condition, and indentation to control execution
  * How `elif` can be used to add more conditional code blocks
  * How `else` can be used to run code when all the `if`'s and `elif`'s are not met. 

#### ► 3.1.1 Modify the code below so it works to print `too slow`

In [ ]:
avg_speed = 10
if avg_speed<15:
    print ("too slow")

too slow


#### ► 3.1.2 Write a series of `if`/`elif`/`else` statements that evaluates the value of `elev_feet` such that:
* If `elev_feet` is less than 400, it prints "too low"
* If `elev_feet` is greater than 500, it prints "too high"
* If `elev_feet ` equal 450, it print "got it!"
* If none of the above conditions are met, it prints "close enough"
* Print "Play again?" after evaluating the "elev_feet" value

In [ ]:
elev_feet = 475
if elev_feet < 400:
    print('too low')
elif elev_feet > 500:
    print('too high')
elif elev_feet == 450:
    print('got it!')
else:
    print('close enough')

close enough


---
### 3.2 `for` loops ([p 38](http://nbviewer.jupyter.org/github/env859/WhirlwindTourOfPython/blob/master/07-Control-Flow-Statements.ipynb))

**3.2.1** Create a for loop that iterates through the items in the list of states and prints them.

In [ ]:
states = ['Maine','Ohio','Kansas','Utah','Alaska','Nevada']
for state in states:
    print(state)

Maine
Ohio
Kansas
Utah
Alaska
Nevada


**3.2.2** Combine a `for` loop and the `range` function to print powers of 2 up to the 8th power of 2 (256)

In [ ]:
for x in range(9):
    print(x, 2**x)    

0 1
1 2
2 4
3 8
4 16
5 32
6 64
7 128
8 256


**3.2.3** *The first line in the code below reads in the contents of the MHK_KS_Weather.csv file and stores each line as item in the list `lineList`.* Iterate through the lines in the `lineList` list and print the <u>length</u> of each line.

In [ ]:
lineList = open('MHK_KS_Weather.csv','r').readlines()
for i in lineList:
    print(len(i))

113
55
54
56
49
57
52
52
54
57
59
54
57
56
56
56
54
54
59
52
56
54
50
54
57
56
56
57
56
56
55
55
54
54
55
57
52
52
54
48
56
54
52
54
59
59
59
56
56
56
59
54
52
56
56
53
57
56
60
54
57
52
53
54
57
57
57
57
54
50
57
54
55
54
55
56
56
54
56
56
57
57


**3.2.4** Extract the 10th line from the lineList to a variable called `line10`. Then use the string `split()` method to break this line up into a new list called `lineData`. *(Note that this is a `csv` file, so values are separated by a comma.)* Finally print each of these items, one at a time.

In [ ]:
line10 = lineList[9]
lineData = line10.split(',')
for i in lineData:
    print(i)

6/9/2023
6
9
2023
160
84.7
61.9
70.3
1.36
4.1
28.5
638.7



---
### 3.3 Iterator and the `range()` function ([p52](https://nbviewer.jupyter.org/github/env859/WhirlwindTourOfPython/blob/master/10-Iterators.ipynb#Iterators))

**3.3.1** Print the phrase "Python is fun!" 5 times using the `range()` function and a `for` loop.

In [ ]:
for i in range(5):
    print("Python is fun!")

Python is fun!
Python is fun!
Python is fun!
Python is fun!
Python is fun!


**3.3.2** Using the `range()` function in a `for` loop, print the every number between 480 and 490.

In [ ]:
for i in range(480,491):
    print (i, end=', ')

480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 

**3.3.3** Using the `range()` function in a `for` loop, print every *other* number between 480 and 490. 

In [ ]:
for i in range(480,491, 2):
    print (i, end=', ')

480, 482, 484, 486, 488, 490, 

---
### 3.4 `while` loops ([p 39](http://nbviewer.jupyter.org/github/env859/WhirlwindTourOfPython/blob/master/07-Control-Flow-Statements.ipynb))

**3.4.1** Write a `while` loop that prints each year, starting at 2017, stops after printing *2020*

In [ ]:
year = 2016
while year<=2019:
    print(year+1)
    year+=1

2017
2018
2019
2020


**3.4.2** The Python `input` function prompts the user to enter a value. Use a while loop to continue asking the user to "pick a number between 1 and 4" until the user guesses correctly.

In [1]:
guess = input("Guess my number, between 1 and 4: ")
actual_number = "1"
while guess != actual_number:
    guess = input("Nope, guess again: ")
    
print ("Got it!, It was " + actual_number)

Got it!, It was 1


### 3.5 `break` and `continue`

In [1]:
#Run this to generate a dictionary of states (keys) and their capitol (values)
state_capitals={"Washington":"Olympia","Oregon":"Salem",
                "California":"Sacramento","Ohio":"Columbus",
                "Nebraska":"Lincoln","Colorado":"Denver",
                "Michigan":"Lansing","Massachusetts":"Boston",
                "Florida":"Tallahassee","Texas":"Austin",
                "Oklahoma":"Oklahoma City","Hawaii":"Honolulu",
                "Alaska":"Juneau","Utah":"Salt Lake City",
                "New Mexico":"Santa Fe","North Dakota":"Bismarck",
                "South Dakota":"Pierre","West Virginia":"Charleston",
                "Virginia":"Richmond","New Jersey":"Trenton",
                "Minnesota":"Saint Paul","Illinois":"Springfield",
                "Indiana":"Indianapolis","Kentucky":"Frankfort",
                "Tennessee":"Nashville","Georgia":"Atlanta",
                "Alabama":"Montgomery","Mississippi":"Jackson",
                "North Carolina":"Raleigh","South Carolina":"Columbia",
                "Maine":"Augusta","Vermont":"Montpelier",
                "New Hampshire":"Concord","Connecticut":"Hartford",
                "Rhode Island":"Providence","Wyoming":"Cheyenne",
                "Montana":"Helena","Kansas":"Topeka",
                "Iowa":"Des Moines","Pennsylvania":"Harrisburg",
                "Maryland":"Annapolis","Missouri":"Jefferson City",
                "Arizona":"Phoenix","Nevada":"Carson City",
                "New York":"Albany","Wisconsin":"Madison",
                "Delaware":"Dover","Idaho":"Boise",
                "Arkansas":"Little Rock","Louisiana":"Baton Rouge"}

**3.5.1** Use a `for` loop and a `break` statement to iterate through states (i.e., the keys) in the `state_capitals` dictionary, printing the name of the state's capitol, stopping when 'Texas' is reached (and not printing Texas' capitol). 

In [4]:
#Loop through the keys in the dict (i.e. states)
for i in state_capitals.keys(): 
#    #Use an if statement to determine if the current state is 'Texas'
        if i=="Texas":
            break
#        #If so, stop iterating immediately
        
#    # Print the dictionary value corresponding with the state
        print(state_capitals[i])

Olympia
Salem
Sacramento
Columbus
Lincoln
Denver
Lansing
Boston
Tallahassee


**3.5.2** Modify the `if` statment and swap the `break` statement with `continue` so that instead of stopping at Texas, the loop  **skips** printing the capital of any state ending with the letter `a`. 

In [8]:
#Loop through the keys in the dict (i.e. states)
for capital in state_capitals.keys(): 
    #Get the capital associated from the current state key
    capital = state_capitals[capital]
    #If the capital ends with 'a'...
    if capital.endswith('a'): 
        #...skip the remainder of the 'for loop' for this iteration 
        #   and move forward to the next item in the list 
        continue
    # Print the dictionary value corresponding with the state
    print(capital)

Salem
Sacramento
Columbus
Lincoln
Denver
Lansing
Boston
Tallahassee
Austin
Oklahoma City
Honolulu
Juneau
Salt Lake City
Santa Fe
Bismarck
Pierre
Charleston
Richmond
Trenton
Saint Paul
Springfield
Indianapolis
Frankfort
Nashville
Montgomery
Jackson
Raleigh
Montpelier
Concord
Hartford
Providence
Cheyenne
Des Moines
Harrisburg
Annapolis
Jefferson City
Phoenix
Carson City
Albany
Madison
Dover
Boise
Little Rock
Baton Rouge


## 6. String Manipulation

**3.6.1** Create a new variable called "all_sports_lower" that has the contents of the `all_sports` string, but using all lowercase letters.

In [10]:
#Create the initial string
all_sports = "Soccer, BASKETBALL, Hockey, Football"
all_sports_lower = all_sports.lower()
print(all_sports_lower)

soccer, basketball, hockey, football


**3.6.2** Use the `split()` function to parse the string into a list variable named "sports". 

In [13]:
sports = all_sports_lower.split()
print(sports)

['soccer,', 'basketball,', 'hockey,', 'football']


**3.6.3** Tweak the code below to print Euler's number ($e$) to 6 decimal places.

In [17]:
e = 2.71828182845904
print(f"{e:.6f}")

2.718282


**3.6.4** Use the variables below to print out the address so it appears as:
```
222 Main St.
Manhattan, KS 66502
```
    

In [20]:
house_number = 222
street_name = "Main st."
city = "Manhattan"
state = "KS"
zip = 66502

print(str(house_number) + ' ' + str(street_name) + '\n' + str(city) + ',' + ' '+ str(state) + ' '+ str(zip))

222 Main st.
Manhattan, KS 66502
